name: Publish Out Theme to out.hajagency.com

on:
   push:
      branches:
         - development

jobs:
   web-deploy:
      name: ðŸš€ Deploy Out Theme to out.hajagency.com
      runs-on: ubuntu-latest
      steps:
         - name: ðŸšš Get Latest Code
           uses: actions/checkout@v5

         - name: ðŸ“‚ Sync Files
           uses: SamKirkland/web-deploy@v1
           with:
              target-server: shishi.oderland.com
              remote-user: hajagenc
              private-ssh-key: ${{ secrets.SSH_KEY }}
              destination-path: /home/hajagenc/out.hajagency.com/wp-content/themes/rb-solutions/
              rsync-options: --dry-run --archive --verbose --compress --delete-after --human-readable --exclude=.git* --exclude=.git/ --exclude=README.md --exclude=readme.md --exclude=.gitignore

         - name: âœ… Done
           run: echo "Deployment to out.hajagency.com complete!"

# https://github.com/SamKirkland/web-deploy
# https://github.com/actions/checkout
# https://stackoverflow.com/questions/58347746/automating-the-build-and-publish-process-with-github-actions-and-github-package
# https://github.com/actions/setup-node